apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: datadog
  name: datadog
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: datadog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/apm-datadog-default: "true"
        io.kompose.service: datadog
    spec:
      containers:
        - env:
            - name: DD_API_KEY
              value: 1165b9e69897f02a730601d4a37d15ae
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_SITE
              value: us5.datadoghq.com
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "notes-service"
            - name: DD_VERSION
              value: "1.0"
          image: gcr.io/datadoghq/agent:latest
          name: dd-agent
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: datadog-claim0
              readOnly: true
            - mountPath: /host/proc
              name: datadog-claim1
              readOnly: true
            - mountPath: /host/sys/fs/cgroup
              name: datadog-claim2
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: datadog-claim0
          persistentVolumeClaim:
            claimName: datadog-claim0
            readOnly: true
        - name: datadog-claim1
          persistentVolumeClaim:
            claimName: datadog-claim1
            readOnly: true
        - name: datadog-claim2
          persistentVolumeClaim:
            claimName: datadog-claim2
            readOnly: true
status: {}
