apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent
  labels:
    app: datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog
  template:
    metadata:
      labels:
        app: datadog
    spec:
      containers:
        - name: dd-agent
          image: gcr.io/datadoghq/agent:latest
          env:
            - name: DD_API_KEY
              value: "669ecb7b6205bd6a4debd89e724e7719"
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_LOGS_ENABLED
              value: "true"
            - name: DD_SITE
              value: "datadoghq.com"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: procdir
              mountPath: /host/proc
              readOnly: true
            - name: cgroups
              mountPath: /host/sys/fs/cgroup
              readOnly: true
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: procdir
          hostPath:
            path: /proc
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup