apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  labels:
    app: notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes-app
          image: horacio1986/notes-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "notes-app-service"
            - name: DD_VERSION
              value: "1.0"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"