apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: notes-app
  name: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: notes-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/apm-datadog-default: "true"
        io.kompose.service: notes-app
    spec:
      containers:
        - env:
            - name: CALENDAR_HOST
              value: calendar
            - name: DB_HOST
              value: db
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "notes-service"
            - name: DD_VERSION
              value: "1.0"    
          image: horacio1986/notes-app:latest
          name: notes-app
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: 
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
